version: "3.7"

services:
  # nginx:
  #   image: nginx:latest
  #   networks:
  #     - laravel-net
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
  #     - "./etc/ssl:/etc/ssl"
  #     - "./projects/:/var/www/projects"
  #   deploy:
  #     # mode: 'replicated'
  #     replicas: 1
  #     placement:
  #       constraints: [node.role == manager]
  #     update_config:
  #       parallelism: 2
  #       delay: 5s
  #       order: stop-first
  #     restart_policy:
  #       condition: on-failure
  nginx:
    image: nginx:alpine
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/ssl:/etc/ssl"
      - "./projects/:/var/www/projects"
    networks:
      - laravel-net
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: 'replicated'
      replicas: 1
      placement:
        # constraints: [node.role == manager]
      update_config:
        parallelism: 2
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
  php:
    image: ashrul/php8:latest
    networks:
      - laravel-net
    volumes:
        - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        - "./projects/:/var/www/projects"
        - "./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
    deploy:
      # mode: 'replicated'
      replicas: 1
      placement:
        # constraints: [node.role == manager]
      update_config:
        parallelism: 2
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
  dbs:
    image: mysql:5.7.22
    configs:
      - source: mysql-config
        target: /etc/mysql/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: salasilah
      MYSQL_DATABASE: salasilah
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - "3306:3306"
    # volumes: 
    #   - "dbs-storage:/var/lib/mysql"
    networks:
      - laravel-net
    deploy:
      mode: 'replicated'
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    networks:
      - laravel-net
    deploy:
      mode: 'replicated'
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 2
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
networks:
  laravel-net:
    driver: overlay

configs:
  mysql-config:
    name: mysql-config
    file: ./configs/my.cnf